title: Hello, world! I'm Keith Sterling
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: keiffster #if your site has a twitter account, enter it here

# Author Settings
author: Keith Sterling # add your name
author-img: keith-sterling.jpeg # add your photo
about-author: A polyglot programmer with an interest in AI related topics, specifically chatbots. All work my own, not my employer # add description
social-twitter: keiffster # add your Twitter handle
social-facebook: keith.sterling # add your Facebook handle
social-github: keiffster # add your Github handle
social-linkedin: keithsterling # add your Linkedin handle
social-email: keith@keithsterling.com # add your Email address

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
